// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qlsnesnqslouejahsyht.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsc25lc25xc2xvdWVqYWhzeWh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MzM0NDYsImV4cCI6MjA3NDQwOTQ0Nn0.t4n1W7JqK_wrA831tUAQcereDsHp5ApAX4K_y4bZfw4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});